server:
  port: 8083 # Standard HTTP/WebSocket port
  address: 0.0.0.0 # Listen on all network interfaces
spring:
  application:
    name: Notification
  grpc:
    server:
      port: 9093
  datasource:
    url: jdbc:postgresql://localhost:5435/notification_db
    username: notification_user
    password: notification_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # Automatically creates/updates the table schema
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username:
      ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  # Logging configuration
logging:
  level:
    com.ismile.core.notification: DEBUG
    org.hibernate.SQL: DEBUG
jwt:
  secret: ${JWT_SECRET:MyVerySecureSecretKeyForJWT2024WithAtLeast512BitsForHS512Algorithm!ChangeThisInProduction}