server:
  port: 8083 # Standard HTTP/WebSocket port
  address: 0.0.0.0 # Listen on all network interfaces
spring:
  profiles:
    active: local
  application:
    name: Notification
  grpc:
    server:
      port: 5053
  datasource:
    url: jdbc:postgresql://localhost:5435/notification_db
    username: notification_user
    password: notification_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # Automatically creates/updates the table schema
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username:
      ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: notification_group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: "*"

  # Logging configuration
logging:
  level:
    com.ismile.core.notification: DEBUG
    org.hibernate.SQL: DEBUG
jwt:
  secret: ${JWT_SECRET:MyVerySecureSecretKeyForJWT2024WithAtLeast512BitsForHS512Algorithm!ChangeThisInProduction}