spring:
  application:
    name: OTP
  grpc:
    server:
      port: 5052
  # Redis configuration
  data:
    redis:
      host: localhost # Use host.docker.internal if running inside a container
      port: 6379
  # Database configuration
  datasource:
    url: jdbc:postgresql://localhost:5434/otp_db
    username: otp_user
    password: otp_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update # Automatically creates/updates the table schema
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  # Kafka Producer configuration
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
kafka:
  topic:
    # This is the property that was missing.
    otp-prefix: "otp"

# Logging configuration
logging:
  level:
    com.ismile.core.otp: DEBUG
    org.springframework.data.redis: INFO
    org.hibernate.SQL: DEBUG

otp:
  security:
    allowed-api-keys:
      - change-me-otp-api-key # Replace with a strong, secret value per client
    public-endpoints:
      - grpc.health.v1.Health/Check
      - grpc.health.v1.Health/Watch
