spring:
  application:
    name: Auth
  grpc:
    server:
      port: 9091
      max-inbound-message-size: 10485760
  datasource:
    url: jdbc:postgresql://localhost:5433/auth_db
    username: auth_user
    password: auth_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  task:
    scheduling:
      pool:
        size: 2
server:
  port: 8081

# JWT Configuration
jwt:
  secret: ${JWT_SECRET:MyDefaultSecretKeyForJWT2024!ChangeThisInProduction}
  expiration: 86400000  # 24 hours in milliseconds
  refresh-expiration: 604800000  # 7 days in milliseconds
  issuer: auth-service

# Logging
logging:
  level:
    com.ismile.core.auth: DEBUG
    org.springframework.grpc: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"