server:
  port: 8080
  http2:
    enabled: true
  ssl:
    enabled: false

spring:
  application:
    name: GrpcGateway

  cloud:
    gateway:
      httpclient:
        ssl:
          use-insecure-trust-manager: true
      routes:
        - id: auth
          uri: h2c://localhost:9091
          predicates:
            - Path=/auth/v1/**
          filters:
            - AddResponseHeader=X-Forwarded-Proto, https
            - RewritePath=/auth/v1/(?<remaining>.*), /${remaining}
